### PR TITLE
Wa extensions

### PR DESCRIPTION
**Pull request by iherman**
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/publ-loc/WA-Extensions.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/publ-loc/2e124c2...f3ec228.html)

### CODE REVIEW

**Comment by iherman** [comment]
This PR contains all the changes to the Selectors and States document and also to the WA model that was discussed. Namely

* Introduction of the Embedded Resource Selector (See https://github.com/w3c/publ-loc/issues/4#issuecomment-334804311)
* Introduction of the Multiple Resource Selector (See https://github.com/w3c/publ-loc/issues/4#issuecomment-334744279 although using a different name)
* Usage of scope.

This PR closes #5, more exactly supersedes it. Note also Issue #2, which to see if the second addition to the document should remain or should be removed.

Similarly, this PR closes #4.

**Comment by azaroth42** [comment]
I would flip the order of 3.10 (`refinedBy`) and 3.11 (`EmbeddedResourceSelector`) but otherwise it looks like a good first cut for discussion.

:+1:

**Comment by iherman** [comment]
I was wondering about that. My problem was that the EmbeddedResourceSelector example makes use of refinement, which may make the example a bit awkward. Maybe a simpler example for that selector and move the current one as an example for refinement. 

However... I do not think the EmbeddedResourceSelector makes too much sense without a refinement...

Ideas?

**Comment by azaroth42** [comment]
Good point. A simpler example for ERS could be:

```
{
  "type": "EmbeddedResourceSelector",
  "value": "/images/logo.jpg"
}
```

For a comment about the logo image embedded in the publication.

**Comment by tcole3** [comment]
Are there any real-world use cases where a component (with its own URL) of a Web Publication is likely to appear (be embedded) in multiple locations within the Web Publication? If so, do any of these use cases require the ability to reference a particular occurrence of the component within the Web Publication? Originally I had thought we might be able to avoid need for ERS through the use of scope, but if we really need to define an ERS anyway, we want to make sure it sufficient to meet as many realistic use cases as possible.

**Comment by iherman** [comment]
> 
> {
>   "type": "EmbeddedResourceSelector",
>   "value": "/images/logo.jpg"
> }
> For a comment about the logo image embedded in the publication.
> 

An aside: you use a relative URL. For the moment ERS refers to URL.

I would propose to put in an issue whether a relative URL is allowed and what the base URL is. Let us get all other things out of the way first...

**Comment by iherman** [comment]
@azaroth42 @tcole3 @BigBlueHat: I will merge this PR. Not because it is a final version, but it may help us to do more fine-grained editings and PR-s.

**Pull request merged**
