### PR TITLE
Minor patches

### PR DESCRIPTION
**Pull request by iherman**
Just minor things that came up during the discussions the past few days...

***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/publ-loc/minor-patch.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/publ-loc/8d9db5c...dae4cd9.html)

### CODE REVIEW

**Comment by iherman** [comment]
@tcole3 if you agree with those minor things, just go ahead and merge this...

**Comment by BigBlueHat** [comment]
So. I may have missed a discussion on this, but this addition (in this PR) concerns me a bit:
>  This specification relies on objects defined in JSON originally defined as part of the Web Annotation Data Model [annotation-model]. In order to ensure backward compatibility, implementations of this specification MUST ignore any additional JSON terms not defined by this specification. 

From: https://s3.amazonaws.com/pr-preview/w3c/publ-loc/8d9db5c...d734ec3.html#json_extensions

This paragraph makes it sound like we're making an entirely unique annotation format for Web Publications, rather than just providing extensions to and guidance for using Web Annotation with (and within) a Web Publication.

Thoughts?

**Comment by iherman** [comment]
Hm. That was certainly not the intention. Rather the opposite: if we have a WP implementation that implements only the Selectors in this spec (e.g., for managing bookmarks), then that implementation _may_ receive JSON Selector objects that may include additional JSON properties related to WA. The only point is that the WP implementation should not reject those JSON object, and should simply ignore the properties it does not understand.

Any better formulation to express that?

**Comment by tcole3** [comment]
Would this work to replace current text of new section 1.1?

This specification relies on a subset of JSON terms originally defined as part of the Web Annotation Data Model [[annotation-model]](#bib-annotation-model) and Vocabulary [[annotation-vocab]](#bib-annotation-vocabulary). This specification extends the definitions of some of these terms in order to satisfy additional use cases, but all uses conforming to original definitions remain valid. This specification also defines additional JSON terms to meet needs of additional use cases.  In order to ensure backward compatibility, implementations of this specification MAY ignore any JSON terms not defined in this specification (directly or by reference to the Web Annotation Data Model and Vocabulary) and MUST NOT treat as invalid any JSON term encountered that is not defined in this specification. 

(Wordy, but we can edit further later.)

**Comment by tcole3** [comment]
I'd like to insert an additional section, 1.2, modeled on 1.3.1 of the Web Annotation data model.

1.2 Conformance requirements related to specific selectors

Not all Selectors defined in this specification are relevant for all Web Publication Resource media types. An implementation MAY therefore ignore certain types of Selectors in case the corresponding media types are not handled by that particular implementation.  Cf. https://www.w3.org/TR/annotation-model/#conformance-requirements-related-to-selectors

**Comment by iherman** [comment]
Thanks @tcole3, I agree with the new wording for 1.1 and also added 1.2 as you proposed. The PR has been updated accordingly.

@BigBlueHat, does this answer your concerns?

**Comment by iherman** [comment]
I'll merge this; we can discuss things further, but no use keeping it as PR

**Pull request merged**
